---
title: "Population Statistics for Countries from 1990-2017"
author: "Cole Pringle"
date: "3/30/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(echo = TRUE, eval = TRUE, fig.align = "center", warning = F, message = F,
tidy=TRUE, tidy.opts=list(width.cutoff=60), R.options=list(max.print=100))
```

```{R}
fert_dat <- read.csv("/stor/home/cdp2653/children_per_woman_total_fertility.csv")
CO2_dat <- read.csv("/stor/home/cdp2653/consumption_emissions_tonnes_per_person.csv")
GDP_dat <- read.csv("/stor/home/cdp2653/gdppercapita_us_inflation_adjusted.csv")
life_dat <- read.csv("/stor/home/cdp2653/life_expectancy_years.csv")

```

## Tidying Data

```{R}
library(tidyr)
library(tidyverse)
library(dplyr)

tidied_fertility <- fert_dat %>% pivot_longer(2:302, names_to="year", values_to="fertility")
tidied_gdp <- GDP_dat %>% pivot_longer(2:61, names_to="year", values_to="GDP_Per_Capita")
tidied_Co2 <- CO2_dat %>% pivot_longer(2:29, names_to="year", values_to="CO2_emission")
tidied_life <- life_dat %>% pivot_longer(2:302, names_to="year", values_to="life_expectancy")

```
After uploading and importing datasets that focus on various statistics for countries across the world, these datasets were then "tidied". This was accomplished by using the pivot_longer function. The datasets originally displayed data for evry year as unique columns. This caused the datasets to be long and unwieldy. By using pivot_longer, year was made into its own variable and column to make the datasets more manageable.

## Joining/Merging Data

```{R}
gdp_life <- tidied_life %>% full_join(tidied_gdp) %>% na.omit()
Co2_gdp_life <- gdp_life %>% full_join(tidied_Co2) %>% na.omit()
full_tidied <- Co2_gdp_life %>% full_join(tidied_fertility) %>% na.omit()
full_tidied <- full_tidied %>% separate(year,into = c(NA,"year"),sep=1,convert=TRUE)


```
Through using the full_join function, I was able to condense the 4 datsets into a single dataset that displayed the variables from every dataset. Full_join was specifically used because the datasets varied in the exact data they displayed. For example, one set might have data from 1800 to 2017, whereas another might have only the years 1990 to 2017. By using full_join, the rows of data that weren't included in all four datasets were removed so that the final joined dataset would be more manageable. Additionally, na.omit was used because certain datasets were missing data for certain rows or columns. By removing these NA values, the dataset is more concise and easily examined.
By joining in this manner, data from several datasets were dropped. The life expectancy and fertility datasets began in the year 1800 but after the join, all years up to 1990 were dropped. Additionally, many countries were dropped from several datasets because the CO2 emissions dataset included only 117 countries whereas others had closer to 180. These extra countries were dropped so that the CO2 dataset could be more effectively compared with the others. The cost of cutting out all this data is that the information that can be gained from examining the joined dataset is more limited than if all data had been preserved.

## Wrangling Data

```{R}
full_tidied %>% filter(year < 2000) %>% select(country, life_expectancy) %>% arrange(desc(life_expectancy))
full_tidied %>% filter(year < 2000) %>% select(country, life_expectancy) %>% arrange(life_expectancy)
full_tidied %>% filter(year >= 2000) %>% select(country, life_expectancy) %>% arrange(desc(life_expectancy))
full_tidied %>% filter(year >= 2000) %>% select(country, life_expectancy) %>% arrange(life_expectancy)
full_tidied <- full_tidied %>% mutate(lifetime_CO2_consumption = life_expectancy*CO2_emission)
full_tidied %>% select(country, lifetime_CO2_consumption) %>% arrange(lifetime_CO2_consumption)
full_tidied %>% select(country, lifetime_CO2_consumption) %>% arrange(desc(lifetime_CO2_consumption))
full_tidied %>% summarize(mean(fertility))
full_tidied %>% summarize(sd(fertility))
full_tidied %>% summarize(var(fertility))
full_tidied %>% summarize(min(fertility))
full_tidied %>% summarize(max(fertility))
full_tidied %>% summarize(quantile(fertility))
full_tidied %>% summarize(mean(GDP_Per_Capita))
full_tidied %>% summarize(sd(GDP_Per_Capita))
full_tidied %>% summarize(var(GDP_Per_Capita))
full_tidied %>% summarize(min(GDP_Per_Capita))
full_tidied %>% summarize(max(GDP_Per_Capita))
full_tidied %>% summarize(quantile(GDP_Per_Capita))
full_tidied %>% summarize(mean(CO2_emission))
full_tidied %>% summarize(sd(CO2_emission))
full_tidied %>% summarize(var(CO2_emission))
full_tidied %>% summarize(min(CO2_emission))
full_tidied %>% summarize(max(CO2_emission))
full_tidied %>% summarize(quantile(CO2_emission))
full_tidied %>% summarize(mean(life_expectancy))
full_tidied %>% summarize(sd(life_expectancy))
full_tidied %>% summarize(var(life_expectancy))
full_tidied %>% summarize(min(life_expectancy))
full_tidied %>% summarize(max(life_expectancy))
full_tidied %>% summarize(quantile(life_expectancy))
full_tidied %>% group_by(country) %>% summarize(mean(fertility))
full_tidied %>% group_by(country) %>% summarize(mean(GDP_Per_Capita))
full_tidied %>% group_by(country) %>% summarize(mean(CO2_emission))
full_tidied %>% group_by(country) %>% summarize(mean(life_expectancy))
full_tidied %>% group_by(country) %>% summarize(sd(fertility))
full_tidied %>% group_by(country) %>% summarize(sd(GDP_Per_Capita))
full_tidied %>% group_by(country) %>% summarize(sd(CO2_emission))
full_tidied %>% group_by(country) %>% summarize(sd(life_expectancy))
full_tidied %>% group_by(country) %>% summarize(var(fertility))
full_tidied %>% group_by(country) %>% summarize(var(GDP_Per_Capita))
full_tidied %>% group_by(country) %>% summarize(var(CO2_emission))
full_tidied %>% group_by(country) %>% summarize(var(life_expectancy))
full_tidied %>% group_by(country) %>% summarize(min(fertility))
full_tidied %>% group_by(country) %>% summarize(min(GDP_Per_Capita))
full_tidied %>% group_by(country) %>% summarize(min(CO2_emission))
full_tidied %>% group_by(country) %>% summarize(min(life_expectancy))
full_tidied %>% group_by(country) %>% summarize(max(fertility))
full_tidied %>% group_by(country) %>% summarize(max(GDP_Per_Capita))
full_tidied %>% group_by(country) %>% summarize(max(CO2_emission))
full_tidied %>% group_by(country) %>% summarize(max(life_expectancy))
full_tidied %>% group_by(country) %>% summarize(quantile(fertility))
full_tidied %>% group_by(country) %>% summarize(quantile(GDP_Per_Capita))
full_tidied %>% group_by(country) %>% summarize(quantile(CO2_emission))
full_tidied %>% group_by(country) %>% summarize(quantile(life_expectancy))

```

I started by looking at how certain facets of the data varied from years before 2000 to after 2000. I then also made a new variable, lifetime CO2 consumption, that is a measure of how much CO2 emission the average person in each country is responsible for over the course of their lifetime. This value was obtained by multiplying the life expectancy by CO2 emission value. Then 6 values, mean, standard deviation, variance, quantiles, maximum, and minimum were determined for all the variables. These same variables were then used when grouping by the country so that the values of the variables could be better understood on a country by country basis.
One important thing to note from the data was an outlier in the life_expectancy values. In 1994, Rwanda had a life expectancy of approximately 9.64 years whereas the second and third lowest values were 44.3 and 44.4 years respectively. This outlier seemed likely to be some sort of mistake as a life expectancy of 9.64 is incredibly low. This value was later removed. On the other end of this variable, the highest life expectancies occurred in Singapore and Japan and sat at around 84 years of age. Average life expectancy was 70.9 years, average CO2 emission was 6.20 metric tons per person, average GDP per capita was 14,890 USD, and the average fertility was 2.83 children per woman.

## Visualization

```{R}
full_tidied %>% select_if(is.numeric) %>% cor %>% as.data.frame %>%  rownames_to_column %>% pivot_longer(-1) %>%  ggplot(aes(rowname,name,fill=value))+geom_tile()+  geom_text(aes(label=round(value,2)))+  xlab("")+ylab("")+coord_fixed()+  scale_fill_gradient2(low="red",mid="white",high="blue") + ggtitle("Correlation Heatmap for Several Population Statistics")

```

This correlation matrix displays how the various variables correlate with each other. The one notable outlying variable from this heatmap is fertility. It has a negative correlation with all other variables whereas all other variables are positively correlated with each other. This makes sense goven that high fertility is often a sign of lesser developed countries and as countries develop their fertility tends to decrease. Every variable other than fertility is associated with advancement or higher quality of living, such as life expectancy and GDP. The year is also positively correlated with all variables except fertility. This suggests that, on average, as time moves forward, countries have increases in CO2 emission, life expectancy, GDP per capita, and lifetime CO2 consumption.

```{R}
all_first_10 <- full_tidied%>%slice(1:280)
ggplot(all_first_10, aes(life_expectancy,GDP_Per_Capita)) + geom_point(aes(color=country, size=CO2_emission), stat = "summary", fun=mean) + scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) + ggtitle("Correlation Between GDP, Life Expectancy, and CO2 Emissions") + ylab("GDP Per Capita (USD)") + xlab("Life Expectancy (Years)")

```

This plot displays statistics for 10 of the countries in the dataset. Life expectancy is displayed along the x-axis, GDP along the Y, CO2 emission is represented by the size of the dots, and the countries or noted by the color of the dots. This plot echoes what was seen in the correlation heatmap and shows that life expectancy, GDP per capita, and CO2 emissions are all positively correlated. The countries with the highest life expectancy and GDP per capita, shown in the top right corner, are Australia, Austria, and Canada. They also have larger than average CO2 emission values. The country most notably located low on life expectancy and GDP per capita is Bangladesh, and it also has noticeably low CO2 emission values.


```{R}
all_first_20 <- full_tidied%>%slice(1:557)
ggplot(all_first_20, aes(year, GDP_Per_Capita)) + geom_point(aes(color=country)) + ggtitle("GDP Per Capita Across 20 Countries From 1990-2017") + ylab("GDP Per Capita (USD)") + xlab("Year")
```

This plot fluctuation in GDP per capita in 20 countries from 1990-2017. Interestingly, countries seem mostly clustered towards either the bottom or the top of the graph, with only a few countries occupying the middle space. Additionally, the countries near the top of the plot, those whose GDP per capita values are already high, seem to be increasing in GDP per capita while most other countries seem to be remaining somewhat stagnant. This seems to suggest that countries which are already well off tend to be the ones improving in GDP per capita whereas less developed countries have been continuing to struggle to improve.

```{R}
ggplot(all_first_20, aes(x=country)) +
  geom_bar(aes(y=life_expectancy, fill=country), stat = "summary", fun=mean) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1), 
        legend.position = "none") + ggtitle("Average Life Expectancy Across 20 Countries") + ylab("Life Expectancy (Years)") + xlab("Country")

```

This plot shows average life expectancy from 1990-2017 for 20 countries. 4 countries stand somewhat noticeably above the others, these being Australia, Austria, Belgium, and Canada. All of these countries are sitting at or just below 80 years as an average life expectancy. The 4 countries with the lowest average life expectancy are Benin, Botswana, Burkina Faso, and Cambodia, and all sit below 60 years.

```{R}
library(cluster)
full_tidied <- full_tidied[-c(2460), ]
cluster_data <- full_tidied%>%dplyr::select(life_expectancy, GDP_Per_Capita, CO2_emission, fertility)
sil_width <- vector()
for(i in 2:10){
  kms <- kmeans(cluster_data,centers=i)
  sil <- silhouette(kms$cluster,dist(cluster_data))
  sil_width[i]<-mean(sil[,3])
}
ggplot()+geom_line(aes(x=1:10,y=sil_width))+scale_x_continuous(name="k",breaks=1:10)
```

```{R}
library(cluster)
pam1 <- cluster_data %>% pam(k=3)

pamclust<-cluster_data %>% mutate(cluster=as.factor(pam1$clustering))
pamclust %>% ggplot(aes(life_expectancy,GDP_Per_Capita,CO2_emission,fertility,color=cluster)) + geom_point() + ggtitle("Cluster Analysis of Relationships Between GDP Per Capita and Life Expectancy") + ylab("GDP Per Capita (USD)") + xlab("Life Expectancy (Years)")
pamclust %>% group_by(cluster) %>% summarize_if(is.numeric,mean,na.rm=T)
full_tidied%>%slice(pam1$id.med)
pam1$silinfo$avg.width
pam_dat<-full_tidied%>%select(GDP_Per_Capita,life_expectancy,CO2_emission,fertility)

pam2 <- full_tidied %>% select(life_expectancy, GDP_Per_Capita, CO2_emission, fertility) %>% scale %>% pam(3)
pam2
clustering_stuff <- full_tidied%>%mutate(cluster=pam2$clustering)
library(plotly)
clustering_stuff%>%plot_ly(x= ~life_expectancy, y = ~GDP_Per_Capita, z = ~fertility, color= ~cluster, type = "scatter3d", mode = "markers") %>%  layout(autosize = F, width = 900, height = 400)
library(GGally)
full_clust <- full_tidied%>%select(life_expectancy,GDP_Per_Capita,CO2_emission,fertility)%>%daisy("gower")%>%pam(k=2,diss = T)
full_tidied%>%mutate(cluster=as.factor(full_clust$clustering))%>%
  ggpairs(columns = 3:6,aes(color=cluster))

```

The results from the cluster analysis further emphasize the negative relationship between fertility and all other variables. 2 clusters was determined to be preferable for examining the data through a silhouette width test. However, the data was also examined by looking at three clusters. In this first plot, the correlation between GDP per capita and life expectancy was examined with the context of using clusters determined using all variables. 3 cluster centers were identified at the data points of 1996 Morocco, 2013 Lithuania, and 2005 Belgium. This means that each of these data points are representative of the average data for a single cluster as a whole.
A 3-Dimensional plot was used in order to help visualize correlations between more than 2 variables, in this case, GDP per capita, fertility, and life expectancy. This plot shows that the cluster with high levels of GDP also has high life expectancy and low fertility. The fertility is particularly low at the extremely high end of GDP per capita.The other 2 clusters are divided largely on the basis of fertility and life expectancy, as both clusters have comparable values for GDP per capita. One of these 2 clusters has low life expectancy, ranging from about 45-70 years, and high fertility, ranging from slightly above 2 all the way up to above 7. The second of these 2 clusters acts as an intermediate between the two other clusters, and has a life expectancy ranging from approximately 55 years up to just above 80 years. The fertility of this cluster ranges from just above 1 to just below 6. The final, multi-paneled plot again reinforces the negative correlation between fertility and the other variables.
